name: Deploy main branch

on:
  push:
    branches:
      - main

concurrency:
  group: deploy_prod
  cancel-in-progress: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.17'
      - name: Install dependencies
        run: |
          cd cdk
          pip install -r requirements.txt
          find lambda -type f -name "requirements.txt" -exec pip install -r {} \;